version: '3.1'
services:
  db:
    image: 'postgres:10'
    volumes:
      - '../docker-appsearch/db:/var/lib/postgresql/data/'
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - main
  rabbitmq:
    restart: always
    image: 'rabbitmq:3.7-rc-management'
    volumes:
      - '../docker-appsearch/rabbitmq-data:/var/lib/rabbitmq'
    env_file:
      - .env
    expose:
      - 5672
    ports:
      - '15672:15672'
      - '5672:5672'
    networks:
      - main
networks:
  main: null
