# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-12 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('company_type', models.CharField(choices=[(b'builder', b'Builder'), (b'rater', b'Rater'), (b'provider', b'Provider')], max_length=100)),
                ('home_page', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('slug', models.SlugField(unique=True, verbose_name=b'slug')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
